### ISSUE TITLE
[enhancement] subdomain are not detected

### ISSUE THREAD

**Issue by nathanaelle** [mozilla/contain-facebook#72] opened 2018-03-29 08:45 UTC
Step to reproduce :

1. open a default container
2. go on https://en-gb.facebook.com/

Suggestion :

  * enforce URL with regular expression not only with white list

**Comment by lucasbfr** [comment] 2018-03-29 11:54
Weird, https://dssadaadssadasd.facebook.com/ opens in the container.

It should work since the regular expression would be valid for any subdomain:
The regular expression used is `^(.*)?${facebookDomain}$`  with facebookDomain being one of `["facebook.com", "www.facebook.com", "fb.com"]`.

**Comment by stoically** [comment] 2018-03-29 12:10
@nathanaelle Do you by chance have the Multi-Account Containers Add-on installed and Facebook assigned to another Container - or installed and disabled? Like stated by @lucasbfr Subdomains normally work fine since they get included by a wildcard match.

**Comment by nathanaelle** [comment] 2018-03-29 12:37
before the installation, I had a previous container named "fb", with www.facebook.com enforced in it.
the installation of "Facebook container" enforced "www.facebook.com" on "Facebook", but nothing else.

I'll try desinstall "Facebook container", remove remaining container, and reinstall …

**Comment by nathanaelle** [comment] 2018-03-29 12:44
before the installation, I had a previous container named "fb", with www.facebook.com enforced in it.
the installation of "Facebook container" enforced "www.facebook.com" on "Facebook", but nothing else.


after desinstall "Facebook container", restart and reinstall, the issue persists.

after desinstall "Facebook container", remove remaining container "fb" and "facebook", restart and reinstall, it's OK and resolve also #71

**Comment by stoically** [comment] 2018-03-29 12:56
Yeah, that's expected behavior then as is stated in the [Description on the Add-on page](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) under "Note"

**Closed** 2018-03-29 15:18 UTC
Labels: MAC-compatibility, as-expected
