### ISSUE TITLE
It doesn't seem to work as advertised?

### ISSUE THREAD

**Issue by WhyNotHugo** [mozilla/contain-facebook#652] opened 2020-06-06 11:46 UTC
- Facebook Container Version: 2.1.1
- Operating System + Version: `Linux aphrodite 5.7.0-arch1-1 #1 SMP PREEMPT Mon, 01 Jun 2020 22:54:03 +0000 x86_64 GNU/Linux`
- Firefox Version: 77.0.1-1
- Other installed Add-ons + Version + Enabled/Disabled-Status: tried on a clean profile too

### Steps to reproduce
1. Visit `web.whatsapp.com`
2. Firefox recommends that I install "Facebook Containers", to keep facebook from tracking me.
3. Makes sense, install addon.
4. Close `web.whatsapp.com` and re open it.

### Actual behavior

1. It doesn't use any container.

### Expected behavior

1. It should use the "Facebook Container".

### Notes

I see that  #182 removed support for whatsapp web due to other issues. If that's the case, then don't prompt me to download the facebook container when visiting web.whatsapp.com -- if you don't do anything for whatsapp users, then don't recommend the addon to those users, it does nothing for them and adds a lot of confusion.

I'm fairly technical and figured out it wasn't working (and narrowed it down to #182), but it might install a false sense of additional privacy to users for whom it's doing nothing.

The real issue here isn't that we can still be tracked on web.whatsapp, but rather that users are being led to believe that it the contrary.

**Comment by maxxcrawford** [comment] 2020-06-09 15:12
@WhyNotHugo On any site not inside the Facebook Container, all Facebook-specific resources (including Facebook analytics and their SDK) are blocked. Technically, Facebook isn't tracking users here, outside of any data sharing outside of Facebook front-end resources. 

However, this extension has changed a lot since #182. I'll reopen that issue and have the team revisit it. Thanks!

**Comment by maxxcrawford** [comment] 2020-06-09 15:13
Duplicate of #558

**Closed by maxxcrawford** 2020-06-09 15:13 UTC

**Comment by WhyNotHugo** [comment] 2020-06-10 07:59
This is not a duplicate of #558. #558 discusses eventually adding whatsapp to the URL list.

My issue here, is that Firefox suggest that I install this extension **now** when I visit web.whatsapp.com. However, the extension does not include whatsapp on the list. You're essentially recommending the extension to an audience for whom the extension does nothing.

The issue here is that `sites for which the extension is recommended` != `sites for which the extension does something`.

It would be prudent to stop suggesting this extension to whatsapp user _until_ #558 has been discussed, resolved and deployed.

**Comment by maxxcrawford** [comment] 2020-06-11 14:40
Fair point. I'm re-opening and making the issue name constructive. Thanks!

**Comment by maxxcrawford** [comment] 2020-06-11 14:41
Related to #558
