### ISSUE TITLE
Duplicate tabs opening

### ISSUE THREAD

**Issue by shapiro125** [mozilla/contain-facebook#48] opened 2018-03-27 17:04 UTC
When a non-Facebook URL is typed into the address bar, the existing tab will go to the page but switch from the Facebook container to the default container. However, a duplicate tab will also open with that same URL.

**Comment by SoftVision-PaulOiegas** [comment] 2018-03-27 17:21
Hi @shapiro125 and thanks for your report! Can you make a screen recording of this issue? I can't seem to reproduce the duplicate tab part on my end.

The part when the non-Facebook link switches from Facebook container to a normal tab is intended however.

**Comment by stoically** [comment] 2018-03-27 17:33
This could be the same problem as described and fixed in https://github.com/mozilla/multi-account-containers/pull/1120

**Comment by shapiro125** [comment] 2018-03-27 17:35
Screen recording -- doesn't happen with every site and the sites I tried are un-assigned.

![recording](https://user-images.githubusercontent.com/7659910/37984210-aa4c8c7a-31c3-11e8-93c3-0b7f1c1bc08f.gif)

**Comment by jmsnll** [comment] 2018-03-28 00:15
I'm having almost the opposite behaviour, where when I navigate to Facebook from any URL a duplicate will open.

![duplicate-tabs](https://user-images.githubusercontent.com/895886/38001562-5bdd6688-3225-11e8-9d20-249651ec7273.gif)

**Comment by SoftVision-PaulOiegas** [comment] 2018-03-28 08:31
Hi @jmsnll I think you are hitting #40. Do you have Multi Account Container installed also?

@shapiro125 Do you have Multi Account Containers installed also? You may be hitting #41.

**Comment by jmsnll** [comment] 2018-03-28 09:08
It doesn't appear that I do @SoftVision-PaulOiegas

**Comment by shapiro125** [comment] 2018-03-28 12:39
I do have Multi Account containers @SoftVision-PaulOiegas, but neither of the tabs in my example are assigned to anything else like the examples in #41

**Comment by stoically** [comment] 2018-03-28 14:34
Multi-Account Containers users experienced this also. It's because of an edge-case regarding canceling of requests and redirects in `onBeforeRequest`. So for Facebook Containers users this can also happen without MAC installed. Add-ons like HTTPS Everywhere make this bug more likely. Fixed it in #55.

**Closed** 2018-03-30 03:19 UTC
Labels: 1.3.0, bug, has PR
