### ISSUE TITLE
How to add a site to allowed sites?

### ISSUE THREAD

**Issue by jepzen** [mozilla/contain-facebook#555] opened 2019-12-14 14:47 UTC
I visit a website and it is says it is blocked from facebook. Great. There is a link to see "Sites that are allowed" but whre do i add pages to be allowed?

**Comment by maxxcrawford** [comment] 2019-12-16 15:37
This is a known issue right now. Follow along on its progress [here](#422). 

Duplicate of #422

**Closed by maxxcrawford** 2019-12-16 15:37 UTC
