### ISSUE TITLE
"Go back one page" button doesn't navigate to the previous page when accessing Web WhatsApp 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#99] opened 2018-04-03 15:47 UTC
*[Affected versions]:*
- Firefox 59.0.2 and above

*[Affected Platforms]:*
- All Windows
- All Mac
- All Linux

*[Prerequisites]:*
- Be logged in a valid WhatsApp account.
- Have the latest Facebook Container add-on installed (v.1.3.0).

*[Steps to reproduce]:*
1. Open the browser with the profile from prerequisites.
2. Open a new tab and navigate to www.web.whatsapp.com website.
3. Click the "Go back one page" button from the top left side of the browser and observe the behavior.

*[Expected result]:*
- "about:newtab" is displayed.
OR
- The "Go back one page" button is greyed out.

*[Actual result]:*
- Nothing happens, the button seems actionable, but it won't navigate to the previous page.

*[Notes]:*
- This issue is not reproducible with the other domains: Instagram, Messenger, and Facebook (in this cases, the button is greyed out).
- A new page that enters into an infinite loading loop is opened after middle clicking the "Go back one page" button - intermittent.
- Here is a screen recording of the issue:

![back button](https://user-images.githubusercontent.com/26000308/38260040-3e242984-376f-11e8-851f-5f5b9da5d1cf.gif)

**Comment by TanviHacks** [comment] 2018-04-04 20:57
@ryanfeeley what do you think about this?  Are we concerned about back button?  Is this a P2 or P3.

**Comment by TanviHacks** [comment] 2018-04-05 23:12
Back button doesn't work to access the previous tab after you switch into a container.  The Container Tab is a completely new tab.

What happens if you undo close tab?

**Comment by TanviHacks** [comment] 2018-04-05 23:14
Or, maybe whatsapp is doing a redirect and that is causing the button not to be greyed out.  Its taking you back to a previous whatsapp page.

**Comment by TanviHacks** [comment] 2018-04-05 23:14
If that is the case, this isn't a bug in the addon.

**Comment by SoftVision-PaulOiegas** [comment] 2018-04-10 14:07
I'll respond for @SoftVision-CarmenFat since she's in PTO the whole week.
> What happens if you undo close tab?

A new tab is opened.

> Or, maybe whatsapp is doing a redirect and that is causing the button not to be greyed out. Its taking you back to a previous whatsapp page.

I think it's doing a redirect behind, maybe checking for the login cookie between the login page and the chat redirect after it finds the login cookie. However, I think pressing the back button should at least do something like a relog.

However, I dug a bit further this and it seems to be a WhatsApp website issue and not a Facebook Container one. Even without the our add-on installed, this behavior occurs. Which means that they probably have a state between the page navigation and log in + display chat, which makes the "Back" button to become active, but not functional.

**Comment by maxxcrawford** [comment] 2020-06-25 15:23
Duplicate of #24

**Closed by maxxcrawford** 2020-06-25 15:23 UTC
Labels: P3, as-expected
