### ISSUE TITLE
https://facebookcorewwwi.onion official tor hidden service not contained

### ISSUE THREAD

**Issue by hairetikos** [mozilla/contain-facebook#146] opened 2018-04-28 01:13 UTC
made a pr here but there may be more domains to add:  https://github.com/mozilla/contain-facebook/pull/147

### Actual behavior
.. not contained

### Expected behavior
.. contain the onion version of facebook

### Steps to reproduce
1. .. run tor browser available at torproject.org
2. .. go to https://facebookcorewwwi.onion or https://m.facebookcorewwwi.onion mobile subdomain

### Notes
.. it is an official facebook onion hidden service with various subdomains and also fbcdn equivalents:

facebookcorewwwi.onion
m.facebookcorewwwi.onion
lm.facebookcorewwwi.onion
l.facebookcorewwwi.onion
fbcdn23dssr3jqnq.onion
... and more

**Comment by groovecoder** [comment] 2019-04-04 15:03
Closing as dupe of #111

**Closed by groovecoder** 2019-04-04 15:03 UTC
Labels: duplicate
