### ISSUE TITLE
Blocking normal anchor link to facebook

### ISSUE THREAD

**Issue by patdavid** [mozilla/contain-facebook#537] opened 2019-10-30 14:54 UTC
- Facebook Container Version: 2.0.3
- Operating System + Version: Win 10
- Firefox Version: 70.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Visiting a page that contains normal anchor links to facebook, the links are disabled:
![image](https://user-images.githubusercontent.com/2778928/67869008-c7101a00-fafa-11e9-8b72-30f488b2b6e6.png)
```
<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.gimp.org/news/2019/06/12/gimp-2-10-12-released/" target="_blank" title="Share this post on Facebook">Facebook</a>
```

Example above is from visiting https://www.gimp.org/news/2019/06/12/gimp-2-10-12-released/

### Expected behavior
That normal anchor links would operate as usual.
For benign anchor links the container shouldn't disable the ability to click on the link.

**Comment by maxxcrawford** [comment] 2019-11-05 17:34
Duplicate of #430

**Closed by maxxcrawford** 2019-11-05 17:34 UTC
