### ISSUE TITLE
Facebook Games Needing Adobe Flash

### ISSUE THREAD

**Issue by Tiny-Owl** [mozilla/contain-facebook#691] opened 2020-10-21 16:47 UTC
Thank you for allowing me to report.
  I am using Firefox browser 81.0.2 (64-bit) and the flash game Bingo bash stalls on loading.
  I like how facebook container stops facebook tracking.

  Is there a way to pause or totally allow Facebook container to allow full operation while on Facebook.
  My fooling around with Facebook Bingo Bash works if I disable Facebook Container.
  While Facebook Container is active Bingo Bash stalls on the loading screen. 

  Thank you.

**Comment by maxxcrawford** [comment] 2020-10-21 16:59
@Tiny-Owl We have [a fix for this](https://github.com/mozilla/contain-facebook/pull/679) that we're going to release soon that addresses this. Facebook Games allows specific third-party scripts to load on the page. By default, Facebook Container blocks them. Our new release respects those few, specific scripts and allows them load, while on the Facebook Games subdomain. 

Duplicate of #663

**Closed by maxxcrawford** 2020-10-21 16:59 UTC
