### ISSUE TITLE
"web.whatsapp.com" link doesn't open in a Facebook Container if the user was previously logged in a WhatsApp account

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/contain-facebook#98] opened 2018-04-03 11:36 UTC
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Be logged in a valid WhatsApp account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" -> Extensions tab and install the Facebook Container v1.3.0.
3. Navigate to https://web.whatsapp.com/ and observe the behavior.

**[Expected result]:**
- The page is opened in Facebook container.

**[Actual result]:**
- The page is opened in normal tab.

**[Notes]:**
- This issue is also reproducible after restarting the browser, and when opening the website in a new browser window.
- This issue is also reproducible if you log out and log in again in your WhatsApp account.
- This issue is not reproducible for https://www.whatsapp.com/.
- Here is a screen recording of the issue:
![fb container - webwhatsapp](https://user-images.githubusercontent.com/31244235/38246979-45e7e2fa-374c-11e8-9a90-e7d4d2a366db.gif)

**Comment by stoically** [comment] 2018-04-04 15:15
I believe this has the same underlying problem as #101

**Comment by TanviHacks** [comment] 2018-04-06 16:09
Duplicate of issue #101.

**Closed** 2018-04-06 16:10 UTC
Labels: 1.4.0, P2, whatsapp

**Comment by heliofbf** [comment] 2018-12-13 23:17
I saw this API that can resolve this problem [www.newapiwhatsapp.com](https://newapiwhatsapp.com) when the Mozilla Firefox not work with WhatsApp. This new API works with all Browsers.
