### ISSUE TITLE
Add site to facebook container from the gate icon

### ISSUE THREAD

**Issue by willthames** [mozilla/contain-facebook#462] opened 2019-07-08 13:05 UTC
The little notification in the top left to allow you to add a site to facebook container is all but invisible (maybe that could be improved?)

Given that there's an exclamation mark on the gate icon, it would be more intuitive to be able to add a site to the Facebook container from that

All the help information is good but would benefit from information about how to add a site to the facebook container

**Comment by maxxcrawford** [comment] 2019-07-08 13:58
The icon should be located over visible login or share buttons. If it's in the top left corner, this is an error. Which site is this happening on?

**Comment by maxxcrawford** [comment] 2019-07-08 19:32
@willthames Please re-open when you provide additional information! Thanks!

**Comment by willthames** [comment] 2019-07-08 23:19
@maxxcrawford any gofundme.com fundraising page (go to the front page and click on any campaign). 

Just tested in a new browser profile with facebook container as the only add-on, just in case it was another extension or userChrome.css interfering - but the behaviour remains as I described

**Comment by maxxcrawford** [comment] 2019-07-09 17:50
@willthames Added GoFundMe support to both share and login elements. I also refactored the badge positioning logic to hide any badges that go to the top left corner.

**Comment by UnderSally** [comment] 2019-07-13 19:24
Editing the allow list needs a lot of work.  Can't seem to find any way to add GoodReads to the list of allowed sites - no option anywhere when I click the link on the page.  This could be resolved by adding a way to manually add sites - I was very surprised the extension did not already have that.

**Comment by Big-Mons** [comment] 2019-07-14 00:59
Facebook container breaks the menu button on a site that I frequent. I'm amazed that there isn't any way to add a site or disable the addon on a specific site. If I click on the fence icon, it shows "_Sites Allowed in Facebook Container_" followed by "_Sites You've Allowed_" and "_None_". I see no way to allow a site.

**Comment by TheSaw** [comment] 2019-07-14 18:50
+1 for this issue.
Currently I can't find a way to log myself back into some websites (e.g. Goodreads) without disabling this extension first. I propose to add a new menu item to the button actions "Allow current site" to manually add it to whitelist.

**Comment by maxxcrawford** [comment] 2019-07-15 12:29
Understood. Adding a site manually, through the add-on panel, is already an open issue. Moving this issue there. 

Duplicate of #422

**Closed by maxxcrawford** 2019-07-15 12:29 UTC

**Comment by maxxcrawford** [comment] 2019-07-15 12:32
@willthames Note that the fix for GoFundMe is still an active PR and will be resolved.

**Comment by 0x3333** [comment] 2020-02-05 15:03
Well, I managed to add a website to Facebook Container:

1 - Inspect the Facebook Container AddOn: about:debugging#/runtime/this-firefox
2 - Click "Inspect" in the Facebook Container
3 - Go to tab "Console" and type: addDomainToFacebookContainer("https://api.whatsapp.com")

You added https://api.whatsapp.com to the URLs in the Facebook Container, now I can use the API without Facebook Container blocking it.

**Comment by maxxcrawford** [comment] 2020-02-12 21:34
Quick note – The PR in review for #422 has this issue: 

![image](https://user-images.githubusercontent.com/2692333/74379320-33164580-4dad-11ea-99b3-592d02d687d1.png)
