### ISSUE TITLE
The "Learn more" link from the door hanger doesn't redirect you to the Facebook Container SUMO page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/contain-facebook#291] opened 2019-04-23 14:17 UTC
[Affected versions]:
- Firefox Nightly 68.0a1 (2019-04-22)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set with the "false" value.
- Have the “facebook_container-2.0.0” add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Facebook Container toolbar button.
3. Click the "Learn more" button and observe the behavior.

[Expected result]:
- The following page is opened in a new tab: https://support.mozilla.org/en-US/kb/facebook-container-prevent-facebook-tracking

[Actual result]:
- The door hanger is dismissed and the SUMO page is not opened in a new tab.

[Notes]:
- This is not reproducible when middle clicking the link or when opening it through the context menu.
- Please see the attached screen recording with the issue:

![learn more](https://user-images.githubusercontent.com/26000308/56588219-98fdca80-65eb-11e9-9606-816196780655.gif)

**Comment by maxxcrawford** [comment] 2019-05-15 15:42
Duplicate of #326. Will be resolved when PR #362 is merged.

**Closed by maxxcrawford** 2019-05-15 15:42 UTC
Labels: P1
