### ISSUE TITLE
How to allow a specific website?

### ISSUE THREAD

**Issue by impala75** [mozilla/contain-facebook#531] opened 2019-10-26 13:56 UTC
Hello,

Sorry, I am not sure it is the right place to ask this.

I would like to know how to allow a specific website, that is, to add it to the container.

For example, there is a blog I like visiting, which embeds Instagram pictures. These pictures are blocked by Facebook Container. How to add this website to the container so that I can see the pictures?

**Comment by maxxcrawford** [comment] 2019-11-05 17:37
This feature is planned for our next major release. See that issues' progress on #422 

Duplicate of #422

**Closed by maxxcrawford** 2019-11-05 17:37 UTC

**Comment by JeremyMrtn** [comment] 2019-11-13 22:55
Waiting for #422 issue, is there a manual way to allow specific websites ?
Thanks for the work already done.
