### ISSUE TITLE
Facebook links opened from 3rd party apps while the browser is closed will not be loaded in a Facebook container tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/contain-facebook#61] opened 2018-03-28 15:08 UTC
[Affected versions]:
- Firefox 59.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.4) installed.
- Firefox is set as your default browser.

[Steps to reproduce]:
1. Start the browser by clicking a Facebook link from a 3rd party application (mail, skype).
2. Observe the opened tab.

[Expected result]:
- The link is opened in a Facebook container tab.

[Actual result]:
- The link is opened in a normal tab.

[Notes]:
- Subsequent links will be opened in Facebook container tabs.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1SeIjNKoCgyJKdHqrC3vL7du_LMrRQ1l9)

**Comment by TanviHacks** [comment] 2018-03-28 21:45
What happens if you then try to login to facebook.com in the normal tab?

Also, instead try this with Multi-Account Containers.
1. Install MAC in a fresh profile
2. Create a Facebook Container
3. Open Facebook Container
4. Go to facebook.com in the Facebook Container tab and select to assign the container
5. Visit facebook.com in a regular Container
6. Answer the prompt to always remember to open facebook.com only in the Facebook Container and proceed to facebook in the facebook container.
7. Close the browser
8. Click a link form an external app to facebook.com

What is the result?

And try it this way too:
1. Install MAC in a fresh profile
2. Create a Facebook Container
3. Open Facebook Container
4. Go to facebook.com in the Facebook Container tab and select to assign the container
5. Close the browser
6. Click a link form an external app to facebook.com

I wonder why we aren't intercepting the request.  A browser startup issue?

Adding @pdehaan

**Comment by pauljt** [comment] 2018-03-28 22:21
I just tested the first STR above, same issue. And while I was testing I think it occurred to me why this doesn't work. We are doing the interception and redirection with  web extensions. When you launch the browser, we open the window as soon as possible. My guess is that the web extensions haven't finished loading yet, and we have already opened the page, so the extension misses the chance to intercept the request. This might be a limitation of the extension APIs - in Firefox OS we had to create a special API for specifically this type of race and I don't believe there is such a mechanism in extensions.  Chrome has a "background" permission[1]  which loads the browser in a hidden state to support this sort of use case. To my knowledge Firefox doesn't support this though.

[1] https://developer.chrome.com/extensions/declare_permissions

**Comment by pauljt** [comment] 2018-03-28 22:29
KNown limitation - we are working on a solution: https://bugzilla.mozilla.org/show_bug.cgi?id=1447551

**Comment by SoftVision-CiprianMuresan** [comment] 2018-03-29 11:50
@TanviHacks, if I try to log in in the normal tab, it is closed and the Facebook container is opened asking me to log in for a second time. The same thing happens if I click on any link from the page.
I've also tried the 2nd STR you mentioned and the same thing as the initial report happens. The website is opened in in a normal tab instead of the assigned Facebook container.

I understand that this is a limitation, but we need to somehow mask this like a silent fail or somehow refresh the page when this happens, at least until [bug 1447551](https://bugzilla.mozilla.org/show_bug.cgi?id=1447551) is fixed. Otherwise people we'll keep reporting that after browser start-up, the add-on no longer works.

**Comment by stoically** [comment] 2018-03-29 12:50
I've added a possible fix in #78

**Comment by stoically** [comment] 2018-03-29 16:17
To elaborate on how the fix in #78 works: The Add-on checks on initialization all open tabs for FACEBOOK_DOMAINS and if a tab is detected, it gets reopened. Since initialization also happens after browser start, tabs that might got opened before the Add-on fully initialized will also reopen in the Facebook Container.

**Comment by TanviHacks** [comment] 2018-04-02 16:55
@stoically Does that mean that facebook.com is first opened in the default container?

That may sound harmless since you aren't logged in, but consider this - you use Thunderbird for email.  You are emailed a facebook link from facebook.  You click on the link - the link has identifying information that ties you to your identity/email address.  The broser loads facebook.com in the default container.  With the load, Facebook thinks they know who you are (even though you have not logged in) and cookies you accordingly.  The browser navigates you to facebook in the Facebook Container.  But its too late - we've polluted the default Container.

**Comment by stoically** [comment] 2018-04-02 17:35
@TanviHacks That's correct, the workaround would work that way. However, if we implement https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377625592 that would no longer be a problem since the cookie is allowed to enter storage, but will never be added to Headers if not in the Facebook Container.

**Comment by TanviHacks** [comment] 2018-04-02 17:46
Okay, then lets go with this for now, and then work on https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377625592 as a followup (since that is more complex).

Should this be in 1.3.0, which we hope to release this week?  Labeling it for now.

**Comment by TanviHacks** [comment] 2018-04-02 17:48
Actually, the PR is quite large.  I'm not sure we want to take that on in 1.3.0, or wait until another release.

**Comment by stoically** [comment] 2018-04-02 17:58
Most of it are structural refactorings to avoid code duplication since this change needs to do the "should this Tab reopened into the Facebook Container or reopened in the Default Container" in two places now: when a request comes in and when initializing for every tab, which makes it look like a large PR. The core logic is still the same.

Essentially moved [this](https://github.com/stoically/contain-facebook/blob/d01d036763afb844c69470a758ba8ca22715081a/background.js#L165-L184) into [this](https://github.com/mozilla/contain-facebook/blob/a13f525de96b67db071c2a0e9d72b3cf7757700a/background.js#L165-L197) to be able to call it from both places.

**Comment by SoftVision-PaulOiegas** [comment] 2018-04-03 08:24
Would have been nice to have this included too. I think it would chop of some current bad reviews where end users reported FC not working at browser start.

**Comment by groovecoder** [comment] 2018-04-05 19:37
I couldn't reproduce this on the latest 1.3.0. I created a profile, installed the 1.3.0 extension, quit the browser.

In IRCCloud app, I clicked a link to "facebook.com", and Firefox Nightly opens with the profile and facebook.com opens in the container tabs.

I even bloated up the profile with a bunch of tabs open to Buzzfeed articles, with `browser.sessionstore.restore_on_demand` set to false so all the tabs would start loading with Firefox startup ... and I still couldn't reproduce. 😢 

Is there any chance this could have been fixed by something already in 1.3.0 ?

**Comment by stoically** [comment] 2018-04-05 19:58
@groovecoder Did you test with the links provided from @SoftVision-CiprianMuresan here https://github.com/mozilla/contain-facebook/pull/78#issuecomment-377532652? Initial page-size seems to be relevant and facebook.com itself is somewhat optimized.

I can't think of any code since 1.2.5 that might fix the issue - also [the relevant test](https://github.com/stoically/contain-facebook/blob/7b1399f6a95663e1e059a78bf4289b669f5882b0/test/features/already-open-reopen.test.js#L42-L75) in #82 goes red without #78

**Comment by pdehaan** [comment] 2018-04-06 18:04
I was unable to reproduce the issue w/ 1.3.1 using some random Facebook page URLs as well as Ciprian URLs from the https://github.com/mozilla/contain-facebook/pull/78#issuecomment-377532652.

**Comment by pdehaan** [comment] 2018-04-06 18:06
Fixed via #78

**Closed by pdehaan** 2018-04-06 18:06 UTC
Labels: 1.3.1, P1, has PR, privacy-issue
