### ISSUE TITLE
Facebook container blocks embed video from facebook in external sites.

### ISSUE THREAD

**Issue by NessunoIM** [mozilla/contain-facebook#438] opened 2019-06-09 21:15 UTC
- Facebook Container Version: 2.0
- Operating System + Version: Windows 10 Pro 64bit 1903
- Firefox Version: 67.0.1 64bit

Site link with problem: https://www.lasicilia.it/video/politica/251430/musumeci-offensivo-parlare-di-ponte-sullo-stretto-in-sicilia-no-e-vi-spiego-perche.html

In this page there is an embed video from facebook, if I disable fb container I can view the video, if fb container is enabled I can't view it.

**Comment by maxxcrawford** [comment] 2019-06-10 17:45
This is as intended for right now. We're adding the ability to toggle off/on site support in the next release that should resolve this.

**Comment by maxxcrawford** [comment] 2019-06-10 17:46
Related: #391 #402 #407

**Comment by brightghost** [comment] 2019-09-11 19:22
This is poor design and the proposed solution is inadequate. Content originating from a Facebook server which is embedded on a page which does not meet the criteria for containerization should simply be loaded as usual without accessing any of the cookies which are stored in the Facebook container. At very least, any intervention by this or any extension that results in selectively blocking content within a page should also inject a placeholder element into the page to make it clear why it has not been loaded. Tracking down why embedded Instagram posts (from the name it was not clear to me this extension also targets Instagram, which I do not have linked to a Facebook account) on web forums were broken was very frustrating and has forced me to discontinue using this extension.

**Comment by maxxcrawford** [comment] 2020-01-12 01:01
Duplicate of #402

**Closed by maxxcrawford** 2020-01-12 01:01 UTC
Labels: as-expected
