### ISSUE TITLE
RFE: add option to allow loading FB resources in non-FB tabs anonymously

### ISSUE THREAD

**Issue by djasa** [mozilla/contain-facebook#521] opened 2019-10-02 22:41 UTC
The extension info specifically says:

> Because you will be logged into Facebook only in the container, embedded Facebook comments and Like buttons in tabs outside the container will not work. This prevents Facebook from associating information about your activity on websites outside of Facebook with your Facebook identity.

I'd like to ask, if it is possible, to add preferences page with a checkbox controlling whether embedded FB content in other containers is blocked as in current version or if it is allowed (then it would make sense to give FB as little client information as possible).

**Comment by maxxcrawford** [comment] 2020-01-08 16:32
Duplicate of #370

**Closed by maxxcrawford** 2020-01-08 16:32 UTC
