### ISSUE TITLE
Reopen in container > Facebook right-click tab menu item not working properly

### ISSUE THREAD

**Issue by Howshall** [mozilla/contain-facebook#457] opened 2019-06-30 17:27 UTC
- Facebook Container Version: 2.0
- Operating System + Version: Windows 8.1 Pro with Media Centre (Windows_NT 6.3)
- Firefox Version: 67.0.4 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Name 	                        Version 	Enabled 	ID
Enhancer for YouTube™	2.0.92	true	enhancerforyoutube@maximerf.addons.mozilla.org
Facebook Container	        2.0	        true	@contain-facebook
Take Webpage Screenshots Entirely - FireShot	0.98.96	true	{0b457cAA-602d-484a-8fe7-c1d894a011ba}

### Actual behavior
Right clicking on an already open tab of logged in Outlook.com or Workplace.com and choosing 'Reopen in container' then 'Facebook' choice, opens that same URL in a new tab, but does NOT open it in a Facebook container tab. Doing the same action but choosing other existing default container like 'Personal' however does.

At the moment I've also found no other way to manually choose to add domains into being loaded within Facebook container without triggering via clicking on Login with Facebook or Facebook share element. Neither of which these 2 sites have.

### Expected behavior
I'd expect 'Reopen in container' > 'Facebook' selection to do exactly as expected and open a new tab but using the Facebook container with all associated cookies and allowed connections to Facebook.

### Steps to reproduce
1. Visit Workplace by Facebook https://www.workplace.com/ (which will likely only load as un-styled HTML text for anyone with Facebook Container addon enabled, as it actually needs to be added to default Facebook Container domains anyway)
2. Right click on that open tab and see 'Reopen in container' context menu
3. In fly-out menu from that option choose 'Facebook'
4. Although a new tab will open it will NOT show as being an active Facebook tab, and the site will still not work properly as most of it's content is being blocked.

**Comment by CharlotteDunois** [comment] 2019-11-10 12:18
I can confirm this issue for any website that is not whitelisted by the addon (and thus not loaded in its FB container).

However this is a real problem to me, as a website that embeds instagram posts can't be loaded, but also can't be moved to the FB container at all to allow embedding instagram.

As an user of this addon I expect of the addon that I can choose to add other domains to the FB container, and not simply have a static maintained list of websites that can only be loaded in the FB container. This issue should be fixed as soon as possible.

**Comment by arganoid** [comment] 2020-02-02 22:10
Can't login to Patreon because of this issue. If I were setting up an account today I wouldn't have chosen login with Facebook - but it's too late for that now, so I have to remove the addon.

**Comment by maxxcrawford** [comment] 2020-06-24 04:07
@CharlotteDunois You can add additionally domains to the Facebook Container. Follow the directions [from the docs](https://github.com/mozilla/contain-facebook/blob/master/docs/container-management.md). Note that the add-on  does not support removing hard coded Facebook-owned domains (like Instagram) currently.

**Comment by maxxcrawford** [comment] 2020-06-24 04:08
@arganoid Adding patreon.com to the Facebook Container should solve any issues with logging into that site via Facebook.

**Comment by maxxcrawford** [comment] 2020-06-24 04:09
@Howshall I'm marking this issue as closed as the add-on now supports adding third-party sites from the panel/doorhanger. Thanks!

**Closed by maxxcrawford** 2020-06-24 04:09 UTC
