### ISSUE TITLE
Facebook container "fence" icon is partially-offscreen at top-left of docs.microsoft.com, until you click the page's "share" menu

### ISSUE THREAD

**Issue by dholbert** [mozilla/contain-facebook#466] opened 2019-07-08 23:59 UTC
- Facebook Container Version: 2.0.1
- Operating System + Version: Ubuntu 19.04 (also repro'd on Win10)
- Firefox Version: Nightly 69.0a1 (2019-07-08) 
- Other installed Add-ons + Version + Enabled/Disabled-Status:  None

### Actual behavior
The fence icon appears at the top-left of the viewport. If you click the "share" menu at the top-right of the page, then the fence icon moves to be over the Facebook entry in that menu dropdown. But as soon as the dropdown closes, the fence icon moves back to the top left of the viewport.

### Expected behavior
No such weird icon at top left of the viewport (covering up nothing in particular)

### Steps to reproduce
1.Visit https://docs.microsoft.com/en-us/windows/client-management/administrative-tools-in-windows-10
2. Click some blank space on the page (needed to make the icon appear for some reason)

**Comment by dholbert** [comment] 2019-07-09 00:03
screencast: https://www.dropbox.com/s/hk6fx4rw3gww52l/fb-container-ms-docs.ogv?dl=0

**Comment by dholbert** [comment] 2019-07-09 00:04
In the screencast, the icon appears (at top-left) at around 0:02 when I first interact with the page (clicking some white space).

It then moves when I click the page's "share" menu, and then moves back to the weird top-left spot when that menu is dismissed.

**Comment by dholbert** [comment] 2019-11-05 03:53
@maxxcrawford looks like you posted a patch (thanks!), but I don't think it landed -- does this need review or anything?  (Not sure about landing procedure here)

I'm back here because I hit this bug again today and was about to file a dupe, only to find that I'd already filed this earlier version. :)

**Comment by DuncanmaMSFT** [comment] 2019-11-06 21:59
Hey folks, just wanted to ask a question here. That 'Facebook' option is just a href to facebook, no script and no tracking. Is there a reason that is being blocked, or is that by design? People keep asking us why we have FB tracking pixels on Docs, which we do *not* have, and every time it is because of this extension showing an icon

@dholbert @maxxcrawford

**Comment by dend** [comment] 2019-11-06 22:09
Adding this Bugzilla report for reference, given that Facebook Container ships by default with Firefox now: https://bugzilla.mozilla.org/show_bug.cgi?id=1594580

**Comment by dholbert** [comment] 2019-11-07 18:33
@DuncanmaMSFT & @dend - thanks for chiming in & sharing those concerns.  I'll defer to @maxxcrawford on an answer there. (I'm not involved with FB-container design/development, personally; I've just filed a few bugs.)

**Comment by maxxcrawford** [comment] 2019-11-07 19:23
@DuncanmaMSFT We have an issue (#430) related specifically to non-tracking elements being badged. We have a solution in the queue, but work hasn't started on it just yet. 

@dend This extension does not ship by default with the browser. It's a recommend add-on (for example, when a user visits Facebook.com but requires users to opt-in. Specifically, this projects' code is entirely separate from the browser code base

**Comment by dend** [comment] 2019-11-07 23:07
@maxxcrawford - you are correct, I've mis-used the term "ships by default". I've validated that it ships as a recommended extension that is likely to be enabled by Firefox customers - the issue still stands. Will add context to #430 on how this affects docs.microsoft.com.

**Comment by maxxcrawford** [comment] 2019-11-11 21:41
@dend Copy that. I set up a project to better show the road map for the project, including how that issue will be prioritized!

**Comment by dend** [comment] 2019-11-14 04:49
Excellent - thank you @maxxcrawford!

**Comment by IVAN980** [comment] 2020-01-14 18:10
Internal 500 server error

**Comment by maxxcrawford** [comment] 2020-06-24 05:06
@dholbert As of right now (on the latest version of the add-on (2.1.1) and Firefox 77.0.1), this looks resolved. Closing for now. Please let me know if these should be re-opened. Thanks!

**Closed by maxxcrawford** 2020-06-24 05:06 UTC
Labels: has PR

**Comment by dholbert** [comment] 2020-06-24 16:25
Yeah, I think this is good.

(Based on my usage, it seems the add-on's UX has been changed so that it no longer shows this "fence" icon by default - it only shows when you hover a facebook button.  That behavior-change on its own causes this issue to go away.)
