### ISSUE TITLE
Facebook container overwriting other containers

### ISSUE THREAD

**Issue by sirati97** [mozilla/contain-facebook#730] opened 2021-02-21 18:06 UTC
I am using workplace with SSO login from google for an organisation I am part of. 

I use both facebook container and google container which makes it impossible for me to login into workplace while keeping sensible separate containment for both google and facebook. (while i mention google container here, google container is innocent) 

# Bug

With the current settings Google SSO login for Workplace is only possible if i force all google sites into the facebook container which is obviously undesired behaviour:
 - facebook container "uncontainerizes" any page it is not responsible for (not in the user list)
 - forces any site to be in the facebook container that is listed in the user list

# Solutions

### Workaround

Google container (a fork of facebook container) has a workaround for this problem by having a setting to make the addon not overwrite other containers. This would work for me.

### Proper solution

fix issue https://github.com/mozilla/contain-facebook/issues/722
while indeed true that facebook TOS does not allow multiple accounts, this issue need addressing as it is possible to have multiple accounts due to other facebook services like Workplace

**Comment by maxxcrawford** [comment] 2021-02-24 17:18
Duplicate of #722

**Closed by maxxcrawford** 2021-02-24 17:18 UTC
