### ISSUE TITLE
Does this add-on stop communication between opened multiple fb tabs?

### ISSUE THREAD

**Issue by vsrawat** [mozilla/contain-facebook#517] opened 2019-09-23 17:27 UTC
I ususally keep both my profile page and my home page opened in different tabs of ff.

Previously, I was seeing that if I click in one fb tab on a pop up notification, or on icon drop down list of notifications, then that information reached to other fb tab also, and all notifications related to that post used to become "have read".

But ever since I installed this add-on, I am finding that even if I read or click a notification, or by clicking it I open the post in some other tab and read or comment there, EVEN THEN, the notification remains very much "NEW" and "UNREAD" in other fb tab?

So I want to ask whether this add-on stops communication between opened multiple fb tabs?

If so, I suggest that is not correct method and is creating difficulties to users as they have to mark notifications as " have read" in all fb tab.

I suggest, the addon should not hinder communication between open multiple fb tabs.

Thanks.

**Comment by ukch** [comment] 2019-10-23 18:59
@vsrawat I use Facebook in the same way. I noticed that FB was doing this even when I don't have this add-on installed, so I suspect the problem is entirely with FB.

**Comment by vsrawat** [comment] 2019-10-24 16:55
OK. Thanks for confirming.
It seems fb has intentionally changed its code so that such acknowledgement of having acted upon a notification is not communicated to other tabs, and even to other pull outs on the same tab.

fb must be having some gain by wasting users bandwidth like this.

Thanks.

**Comment by maxxcrawford** [comment] 2019-11-05 17:38
@ukch @vsrawat Understood. Closing this issue for now.

**Closed by maxxcrawford** 2019-11-05 17:38 UTC
