### ISSUE TITLE
Facebook workplace with microsoft SSO doesn't work

### ISSUE THREAD

**Issue by pauljt** [mozilla/contain-facebook#70] opened 2018-03-29 03:22 UTC
Report via email: 

My workplace uses Workplace by Facebook (https://www.facebook.com/workplace) and it does not work with the Facebook Containers add-on installed in Firefox. Facebook Containers is still active since it uses the Facebook domain when accessing Workplace by Facebook (http://work.facebook.com)

What happens when trying to login is a perpetual loop where it opens our single sign-on page (in this instance Microsoft) only to close it again. Keeps happening until you close the tab.

**Comment by pdolanjski** [comment] 2018-03-29 15:09
I'm marking as a nice to have for now.  If someone has compelling evidence that Workplace actually has significant adoption, we can potentially raise the priority.

**Comment by ryanfeeley** [comment] 2018-03-30 21:07
@pauljt Would being able to add Microsoft SSO properties into he Facebook container help? Something like this:
![oculus](https://user-images.githubusercontent.com/68213/38153855-cf2de90a-343c-11e8-8778-bb19a560f8ac.png)

**Comment by Acid-Crash** [comment] 2018-04-06 09:15
Hi, I also have a similar issue. My company uses single sign-on. When trying to login I end up with the following message.
"The link you followed may be broken, or the page may have been removed."

**Comment by heejeroen** [comment] 2018-04-10 07:56
Same issue here, our company is using ADFS for single sign-in. After logging in, I receive a 404 message saying Workplace cannot find the saml.php page.

**Comment by AlexCzar** [comment] 2018-04-25 07:57
We have the same issue, although at least instead of permanent loop when we try to log in to facebook workplace we get just this error page:
URL: https://twino.facebook.com/work/saml.php
error message:
This page isn't available
The link you followed may be broken, or the page may have been removed.

**Comment by Acid-Crash** [comment] 2018-06-22 12:45
Hi, are there any updates on this?

**Comment by safwanrahman** [comment] 2018-08-30 07:52
Its also not working with single sign on with Google accounts! Its having infinity redirect!

**Comment by hajder** [comment] 2018-09-12 19:41
Also wanted to report this issue with Google SSO and Workplace. Users get stuck at https://company.facebook.com/work/saml.php with a 404 error.

Having an option to add Google to Facebook container should be enough I think.

**Comment by natilux2** [comment] 2019-02-18 08:04
My F@W still not working . Any update or something similar ?

**Comment by groovecoder** [comment] 2019-02-19 16:07
Nothing yet, but we are triaging and prioritizing these issues, so upvotes are helpful!

**Comment by ralfbergs** [comment] 2019-05-06 10:08
> I'm marking as a nice to have for now. If someone has compelling evidence that Workplace actually has significant adoption, we can potentially raise the priority.

My company are also using it now, and we're 60+K users, all using Microsoft SSO...

Would really appreciate you adding support for that...

**Comment by groovecoder** [comment] 2019-05-06 14:35
We are working on a release that will allow users to add sites into the Facebook container when trying to log in. We designed it for the use-case where someone uses Facebook as their SSO provider, but it may help this situation too. Please watch this space and help us test it when it's released.

**Comment by Acid-Crash** [comment] 2019-06-05 13:07
Hi,
The issue is still here.
Have you added the mentioned "add site into the Facebook" in the lates release (Facebook Container 2.0)?

**Comment by maxxcrawford** [comment] 2019-06-05 15:36
@Acid-Crash Yes – But we only support that feature on sites that have "Login with Facebook" on sites outside of the Facebook Container. 

Example: https://imgur.com/signin

![image](https://user-images.githubusercontent.com/2692333/58969567-8bf10100-877d-11e9-9f95-7275849d30df.png)

If I'm reading the issue correctly, the sign in method is using Microsoft SSO INSIDE the Facebook Container (on Workplace) and attempts to connect outside the container to MSFT, breaking the log in process. 

We have a feature in the works to manually add sites to the Facebook container. Follow it here: #422

**Comment by maxxcrawford** [comment] 2019-06-05 18:54
Closing this issue for now. As mentioned, I referenced this issue in #422 to be part of the testing params. Thanks!

**Closed by maxxcrawford** 2019-06-05 18:54 UTC
Labels: P3, enhancement

**Comment by Integrator9004** [comment] 2020-01-21 10:34
Same problem at my work.  Is this enough evifdence that this is more than a "nice to have" now?

**Comment by mazilu88** [comment] 2020-01-27 08:19
I am also having this problem "Facebook workplace with microsoft SSO doesn't work". Why is this issue closed?

**Comment by yoctozepto** [comment] 2020-03-11 17:22
Still applicable, the #422 does not fix this, it's impossible to remove workplace from container.

**Comment by maxxcrawford** [comment] 2020-03-11 17:24
@yoctozepto I think it is the inverse – the fix for this is to add Microsoft.com (which covers its' subdomains) to the Facebook container.

**Comment by yoctozepto** [comment] 2020-03-11 17:38
Thanks, @maxxcrawford, I misread last comment. I had to add "microsoftonline.com" but now all other microsoft sites, including office, go crazy with broken redirects... I guess one can't have the cake and eat it too.

**Comment by maxxcrawford** [comment] 2020-03-11 17:39
@yoctozepto Ugh. I imagine you'll need to continue to add those sites to the Facebook container too to get past the redirects. It's a bit of a goose chase. 😦

**Comment by TonyCr46** [comment] 2020-04-23 02:35
I'm going to piggyback on this topic because I think my problem is related.

I'm getting a 403 Error: app_not_configured_for_user when I try to open my university's Workplace page. This was working fine until this morning. I had powered down the computer last night and it began when I restarted today. I suspect this may be coincidental since I have done this several times within the past few days (storms in the area). This is happening on MS Edge for Mac, which is my preferred browser. I _was_ able to log in to Workplace from Safari. 

Here is a screenshot of the error info:

![Workplace error](https://user-images.githubusercontent.com/8091195/80052462-eeddb900-8544-11ea-82f0-bd5ab7ec0233.png)

Thanks for the help.

**Comment by maxxcrawford** [comment] 2020-04-23 04:01
@TonyCr46 Are you using this extension in other browsers? Facebook Container is currently only supported in Firefox desktop (due to [Containers](https://support.mozilla.org/en-US/kb/containers) technology).

**Comment by TonyCr46** [comment] 2020-04-23 07:44
@maxxcrawford I'm not sure what you mean by extension. This is happening when I open the web page xxxuniversity.workplace.com. It was working in Edge up until yesterday. It's working fine in Safari now.

**Comment by yoctozepto** [comment] 2020-04-23 07:53
@TonyCr46 this is a bug report against Mozilla's Facebook Container extension to Firefox desktop, not Facebook. (BTW, xxxuniversity sounds very NSFW ;-) )

**Comment by TonyCr46** [comment] 2020-04-23 08:12
OOPs. My mistake. Thanks for the heads-up.

**Comment by X3MBoy** [comment] 2021-09-22 20:47
Up to today, I still have this issue

**Comment by leonmoonen** [comment] 2022-03-07 10:05
This issue is still not solved for workplaces that use Microsoft SSO, #422 does not solve it, adding Microsofts login sites to Facebook Container gives problems for all other sites that Microsoft SSO. Adding all those sites to Facebook Container may remove the login issue but completely defeats the purpose of having a container in the first place...

**Comment by activivan** [comment] 2023-09-24 11:21
Issue remains with Google SSO as well
