### ISSUE TITLE
Cookies are removed in Non-Facebook Containers for Multi-Account Containers assigned Domains

### ISSUE THREAD

**Issue by stoically** [mozilla/contain-facebook#112] opened 2018-04-05 21:55 UTC
Affected Facebook Container Version: 1.3.0

With the change in #94 all cookies are removed in Non-Facebook Containers on Add-on initialization even when cookies belong to URLs that are assigned with Multi-Account Containers. So MAC users have to login again to assigned URLs after every browser restart.

**Comment by pdehaan** [comment] 2018-04-06 18:39
I believe this was fixed via PR #114.

Unable to reproduce locally in 1.3.1.

But in case I'm missing something obvious, here were my steps:

1. Install MAC via about:addons.
1. Create a new "Social" tab group, and assign messenger.com to it.
1. Log into messenger.com (which forces login through Facebook).
1. Install Facebook Container v1.3.1 [beta] via about:debugging; since it's currently unsigned.
1. Go to www.facebook.com (which correctly opens in Facebook container and is not logged in).
1. Go to www.messenger.com (which correctly opens in my old Social MAC container and is still logged in).

**Closed by pdehaan** 2018-04-06 18:39 UTC
Labels: 1.3.1, MAC-compatibility, P1, has PR

**Comment by stoically** [comment] 2018-04-06 18:41
@pdehaan yep, those are the correct STR, thanks for testing!
