### ISSUE TITLE
Problem with spotify login - Redirect Loop

### ISSUE THREAD

**Issue by wellington1993** [mozilla/contain-facebook#511] opened 2019-09-04 21:31 UTC
- Facebook Container Version: 2.0.2
- Operating System + Version: Lubuntu 19.04
- Firefox Version: 71.0a1 (2019-09-04) (64-bit)

### Actual behavior
There is a redirect loop in previously logged spotify player sites, when use Facebook credentials to login.

Causing loop in that links:
- https://accounts.spotify.com/login/?_locale=pt-BR&continue=https%3A//www.spotify.com/br/account/overview/
- https://www.spotify.com/br/account/overview/

The problem not occurred in private mode because the add-on is desabled automatticaly.

### Expected behavior

- No loop 
- Spotify login working
- Add-on working in previously logged sites.

### Steps to reproduce
1. Login in Spotify without add-on with Facebook login
2. Install add-on
3.Try to login again

### Notes
Thanks.

**Comment by wellington1993** [comment] 2019-09-04 22:14
I only can login after disable the add-on:
https://open.spotify.com/browse/featured

**Comment by jlcx** [comment] 2019-09-06 15:20
I believe I'm having a similar issue with meetup.com login (2.0.2, FF 69.0, Ubuntu 18.04).  I click "allow", but it allows only for secure.meetup.com, and then I'm redirected back to meetup.com.  Perhaps "allow" should be for the entire domain by default, or at least that should be an option people can select?

**Comment by madox2** [comment] 2019-10-20 12:10
I am having the same problem at [https://www.luddie.org](https://www.luddie.org). Is there a workaround that can be implemented without forcing users to disable this extension?

**Comment by rcsilva83** [comment] 2020-02-27 17:42
Same problem here - I have to disable the extension before login. It's funny because I don't use Facebook Login on Spotify anymore.

**Comment by maxxcrawford** [comment] 2020-03-03 16:23
This has been fixed and will be in the next release! 

Duplicate of #567

**Closed by maxxcrawford** 2020-03-03 16:23 UTC
Labels: 2.1-p2

**Comment by madox2** [comment] 2020-09-26 08:24
Still the problem. It allows me to log in for the first time but when I log out and try to log in again it won't let me. I need to do force refresh (ctrl + f5) to be able to log in again.
