### ISSUE TITLE
You can still share a blocked site by using middle click

### ISSUE THREAD

**Issue by obotisan** [mozilla/contain-facebook#376] opened 2019-05-20 14:11 UTC
**Affected versions:**
- Firefox 67.0

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.3](https://github.com/mozilla/contain-facebook/releases/tag/1.7.3) add-on installed.

**Steps to reproduce:**

1. Go to a site that has the share button locked, for example [this link](https://www.aliexpress.com/item/Free-Shipping-Livolo-Luxury-White-Crystal-Glass-Switch-Panel-EU-Standard-VL-C701-11-110-250V/512886492.html).
2. On the right side of the screen click by using middle-click on the Share button.  

**Expected result:**
- The facebook container prompt will appear.

**Actual result:**
- A new tab is open and you are able to share the post, even though the button should be locked..   

**Notes:**
- This issue is reproducing on a lot of other sites, too. 
- Please see the attached screencast with the issue: 
![middle click still works](https://user-images.githubusercontent.com/42799381/58027770-06851400-7b22-11e9-8f84-52065932f9c2.gif)

**Comment by maxxcrawford** [comment] 2019-05-20 15:44
Leaving a link for myself (or anyone who tackles this issue): 
https://stackoverflow.com/questions/1795734/triggering-onclick-event-using-middle-click

**Comment by maxxcrawford** [comment] 2020-06-24 04:02
Duplicate of #375

**Closed by maxxcrawford** 2020-06-24 04:02 UTC
