### ISSUE TITLE
Wrong information is displayed inside the Facebook Container's panel regarding the AMO page  

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/contain-facebook#237] opened 2019-03-26 15:38 UTC
**[Affected versions]:**

- Firefox 66.0.1 (BuildId:20190322013140).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.12.6

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.5
3. Access the following [webpage](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/).
4. Click the "Add to Firefox" button.
5. Click the "Add" button from the permission panel.
6. Click the Facebook Container button.

**[Expected result]:**

The Facebook Container panel's information states that the AMO page **is not** inside the Facebook Container.

**[Actual result]:**

The Facebook Container panel's information states that the AMO page **is** inside the Facebook Container.

**[Additional Information]**
The wrong information is displayed right after the addon is installed.
I have attached a screencast for this issue.

![wrong info](https://user-images.githubusercontent.com/28087895/55010810-8fce0d80-4fed-11e9-816f-d5c917ca242d.gif)

**Comment by stoically** [comment] 2019-03-26 15:48
That's probably a duplicate of #228

**Comment by groovecoder** [comment] 2019-03-26 16:07
Yes, I think #228 is the same issue.

**Closed by groovecoder** 2019-03-26 16:07 UTC
