### ISSUE TITLE
Does this require Multi-Account Containers to be installed and active?

### ISSUE THREAD

**Issue by jsocol** [mozilla/contain-facebook#59] opened 2018-03-28 12:52 UTC
When I first installed the Facebook Container extension, it didn't work, even after restarting the browser. I had to activate Multi-Account Containers, then deactivate and reactivate Facebook Container, to get the expected behavior.

That's OK (though I don't entirely see why it's necessary) but it's not clearly documented. The [blog post](https://blog.mozilla.org/firefox/facebook-container-extension/) didn't make that clear at all, and the README in this repo actually seems to indicate that Multi-Account Containers is _not_ a requirement, but is an additional option if you like Facebook Container.

So if it's intentional that Multi-Account Containers is required to use Facebook Container, it should be clearly documented. If it's not intentional, it does appear to be a requirement at the moment.

**Comment by jsocol** [comment] 2018-03-28 12:54
I should add as a detail that I had Multi-Account Containers installed but not active, so Container Tabs was already turned on when I installed Facebook Container.

**Comment by karolyipeter** [comment] 2018-03-28 13:40
It is not a requirement. I don't have `Multi-Account Containers` installed only `Facebook Container` and it works fine.

Try uninstalling `Multi-Account Containers` so we can check if the problem is caused by that being disabled.

**Comment by stoically** [comment] 2018-03-28 14:22
It's not a requirement.

What you experienced is bug regarding being Multi-Account Containers being deactivated when installing Facebook Container. Facebook Container [checks if MAC is installed](https://github.com/mozilla/contain-facebook/blob/99bec758fb0a79ce43f36fe71a14998abfa61908/background.js#L17), but it doesn't check if the Add-on is `enabled` or not. It then proceeds to [send a message to MAC, which will reject the Promise](https://github.com/mozilla/contain-facebook/blob/99bec758fb0a79ce43f36fe71a14998abfa61908/background.js#L24), and in this case completely cancel initialization because the call isn't try/catch'ed.

**Comment by jsocol** [comment] 2018-03-28 14:58
Sounds like this is already understood, that's awesome! If I can provide more help or information let me know.

**Comment by jonathanKingston** [comment] 2018-03-28 15:29
I'm going to close this as I think this has been covered in #59. Thanks for raising.

**Closed by jonathanKingston** 2018-03-28 15:29 UTC

**Comment by SoftVision-CarmenFat** [comment] 2018-03-29 15:31
Tested this issue with Facebook Container version 1.2.5, on Firefox Release 59.0.2, Beta 60.0b7 and Nightly 61.0a1 (2018-03-29), across platforms: Windows 10 x64, Ubuntu 14.04 x64 and macOS 10.12.6.
The Facebook Container add-on now works as expected even though Multi-Account Containers is disabled.
