### ISSUE TITLE
False Positive Blocking of Safe, Non-Tracking Links to Facebook

### ISSUE THREAD

**Issue by technotarek** [mozilla/contain-facebook#516] opened 2019-09-23 15:33 UTC
- Facebook Container Version: 2.0.2
- Operating System + Version: MacOS Mojave 10.14.6
- Firefox Version: 69.0.1

### Actual behavior
Some websites use "safe" links that allow users to share a page on Facebook without loading any of Facebook's sdk / javascript. They don't permit the tracking that Facebook Container is meant to prevent and should be allowed. Instead, Facebook Container is disabling the links and injecting "Facebook Container has disabled this button and blocked Facebook from tracking your visit to this page." 

Example page: 
[https://attic.city/item/8Ho/vintage-danish-modern-brouer-rosewood-credenza-by-mcmsanfrancisco/mid-century-modern-san-francisco](https://attic.city/item/8Ho/vintage-danish-modern-brouer-rosewood-credenza-by-mcmsanfrancisco/mid-century-modern-san-francisco)

### Expected behavior
Do not block; allow link to behave normally.

### Steps to reproduce
1. See provided link.

### Notes
The technique uses on the example page is similar to but may not exactly match non-js implementations used by others (e.g., https://sharingbuttons.io).

**Comment by maxxcrawford** [comment] 2019-09-23 15:41
Duplicate of #430

**Closed by maxxcrawford** 2019-09-23 15:41 UTC
