### ISSUE TITLE
Missing Badge and pop up displayed under underlay on airbnb.ca

### ISSUE THREAD

**Issue by e-pang** [mozilla/contain-facebook#323] opened 2019-05-09 01:46 UTC
go to https://www.airbnb.ca/
1. Click the sign in button - the badge doesn't show up on the 'log in with facebook' button.
2. When the button is clicked the incontext pop appears under the underlay 
<img width="1077" alt="Screen Shot 2019-05-08 at 12 40 25" src="https://user-images.githubusercontent.com/30128313/57421470-fee87580-71d9-11e9-847b-9179707434fb.png">

3.The incontext pop up stays even when the sign in prompt is gone.
<img width="1476" alt="Screen Shot 2019-05-08 at 12 43 00" src="https://user-images.githubusercontent.com/30128313/57421471-fee87580-71d9-11e9-93b4-ac7cccbfdf2a.png">

**Comment by maxxcrawford** [comment] 2019-05-15 16:11
Duplicate of #312

Adding this site to that issue.

**Closed by maxxcrawford** 2019-05-15 16:11 UTC
Labels: P1
