### ISSUE TITLE
Facebook Container 2.3.3 messes up with font size and colors

### ISSUE THREAD

**Issue by mdorier** [mozilla/contain-facebook#863] opened 2022-09-08 13:30 UTC
- Facebook Container Version: 2.3.3
- Operating System + Version: Mac OS 12.5.1
- Firefox Version: 104.0.2
- Other installed Add-ons + Version + Enabled/Disabled-Status:

I'm on Mac OS 12.5.1 with Firefox 104.0.2 and the latest version of the Facebook Container plugin (which I have been using for years without any issues). Right now it started messing up fonts on some websites. For instance on Wikipedia it reduces the font size. On Github it reduces the font size and some text is left black even on Github's dark mode, when it should be white.

**Comment by kutiny** [comment] 2022-09-08 13:36
I have the exact same problem (same SO + plugin + firefox version)
In addition I saw a problem with content_script.js on line 694
`for (let item of target.querySelectorAll(querySelector)) {`
TypeError: target.querySelectorAll is not a function

**Comment by kutiny** [comment] 2022-09-08 13:37
Dup: #862

**Comment by multun** [comment] 2022-09-08 13:39
the root cause is [this change](https://github.com/mozilla/contain-facebook/commit/00ded7623f2615a3a81271907b8feecf011acfbb) by @codemist which adds new CSS to the `body` of all sites, not just facebook-related elements

**Comment by zelch** [comment] 2022-09-08 13:53
Yep, between that change and 2b141da0635f918901bdd531e3db89f3479867f2, the result breaks a good chunk of the websites that I use.

And since I also use Dark Reader, the impact is even bigger.

I spent a good half hour+ trying to figure out what was breaking everything.

**Comment by LoZeno** [comment] 2022-09-08 13:55
Just adding myself to the list of people affected by this issue, lots of the website I visit have black text on black background if I keep Facebook Container active while using dark mode. I'm on Windows and using Firefox Developer Edition 105.0b8

**Comment by bakulf** [comment] 2022-09-08 14:04
Version 2.3.3 was buggy and, as a temporary fix, we just released a v2.3.4 as a v2.4.2 repackaged. Please, update the add-on to have a fix for this issue.
All the features introduced by v2.3.3 will be released in v2.3.5 as soon as possible.

**Closed by bakulf** 2022-09-08 14:04 UTC
