### ISSUE TITLE
Can't load 929.org.il, no option to allow in FB container

### ISSUE THREAD

**Issue by marcstober** [mozilla/contain-facebook#495] opened 2019-08-09 06:06 UTC
- Facebook Container Version: 2.0.1
- Operating System + Version: Win 10
- Firefox Version: 68.0.1 (68 bit)

### Actual behavior
1. Visit the following URL: https://www.929.org.il/lang/en/page/154/post/49323
2. A purple exclamation point appears on the extension's fence icon in the top toolbar.
3. All the content of the page disappears (after a brief flicker)!
4. Clicking on the fence icon, and then "sites you've allowed" it says I can allow sites in the container, but there are no options to do this.

### Expected behavior
1. Ideally, the site would work outside of the Facebook container.
2. If not, I'd expect an "allow this site in the Facebook container" option in the pop-up to make an exception for this site.

**Comment by maxxcrawford** [comment] 2019-08-09 20:26
Looks like this site completely shuts down when the SDK is blocked. (I tested the site with ["Strict" ETP](https://support.mozilla.org/en-US/kb/content-blocking?as=u&utm_source=inproduct#w_how-to-block-more-or-fewer-trackers) turned on, which also blocks the SDK from loaded and it breaks. We have a solution in the works where you can add any site to the Facebook containter. Follow it here: #422

**Comment by maxxcrawford** [comment] 2019-08-09 20:26
Duplicate of #422

**Closed by maxxcrawford** 2019-08-09 20:26 UTC
