### ISSUE TITLE
going to facebook messes up history

### ISSUE THREAD

**Issue by triadne** [mozilla/contain-facebook#695] opened 2020-11-02 17:09 UTC
When I am browsing, if i click on a facebook link, it takes  me to facebook, but then I cannot click back any more. 
further examination shows that when I click on a facebook link, it closes my current tab and open the facebook link in a new tab. this is ugly behaviour and is unaccaptable.  if you are going to open facebook in a facebook container tab, this is desirable certainly, but it is not desirable to lose the website that i travelled to facebook from. just open the new facebook tab and leave the old tab there. 
or at the very least add an option for it.

**Comment by Yrkan** [comment] 2020-11-02 20:05
Agree, i don't know why it opens a new tab. but if it is necessary maybe give the new tab the history of the one closed ?

**Comment by groovecoder** [comment] 2020-11-11 20:06
Dupe of #24 .

**Closed by groovecoder** 2020-11-11 20:06 UTC
Labels: duplicate
