### ISSUE TITLE
help please, new container user

### ISSUE THREAD

**Issue by shineona** [mozilla/contain-facebook#659] opened 2020-06-17 04:10 UTC
Hi, thanks so much for your work. Quick question: 

It does not load the Facebook page "...in a new blue colored browser tab (the “Container”)" as it says, but rather just looks the same as usual, and the container icon remains grey (i thought perhaps it would turn the reddish colour as in the extensions library to indicate it is active?)

I just want to make sure its actually working in this case, ie with no new blue tab. 
Im a strongly security/privacy/anti surveillance-capitalism type "ordinary user", on a MacBook Pro, latest mozilla, Nord vpn, Bitwarden password manager, settings as per your instructions. 

Further to this- I was wanting a way to "sandbox" Facebook...I use safari for everything else, and thought by using firefox only ever for Facebook and nothing else, with your container, privacy badger etc etc, that this might be an effective way to at least reduce and limit facebooks tentacles. 
Am I right in this thinking?
Kindly,
Mark

**Comment by maxxcrawford** [comment] 2020-06-23 15:22
Mark – Thanks for filing. The tab color is a known issue, #386. 

However, your thinking is correct. By only using Facebook on Firefox (along with this extension), you're sand boxing Facebook on this computer. _Note that using the app, or signing in on other devices/browsers, they can still track you. _

Duplicate of #386

**Closed by maxxcrawford** 2020-06-23 15:22 UTC

**Comment by shineona** [comment] 2020-06-27 11:36
Thankyou very much.
I love this add-on, and would be very happy to pay for it. Would be great if it was available for iOS and safari, but im sure thats too hard thanks to apple.
Did I read correctly somewhere that Container will soon no longer work on macOS?
