### ISSUE TITLE
Facebook Container Causes "View this post on Instagram" Placeholder Instead of Image

### ISSUE THREAD

**Issue by UbuntuMetal** [mozilla/contain-facebook#407] opened 2019-05-26 03:52 UTC
Hi. I finally found the answer as to what was causing Instagram images in news articles etc to not be shown, with only a blank box, camera icon, and "View this post on Instagram" link instead: the Facebook Container extension.

For example, at:

[https://www.news.com.au/entertainment/tv/game-of-thrones/game-of-thrones-star-sophie-turner-shows-off-surprise-new-look/news-story/7dbaa2f483187a84dca95bb0a762d5d3](url)

... I get the placeholder (shown in the screenshot attached) for the 2nd and 3rd images. In Chrome, it is fine, but not in Firefox, so I eventually tracked down this extension as the culprit. I did search for info on how to whitelist sites for this extension, but found nothing. So, while I can just disable the extension and all is fine, I thought I better report this so hopefully this issue can be remedied, especially since so many web sites, especially news one, increasingly include images fed in from Instagram. Cheers.

![Instagram](https://user-images.githubusercontent.com/41879371/58377108-b47a3d80-7fbc-11e9-9edd-8f919dc9c7dd.jpg)

- Facebook Container Version: 1.9.1
- Operating System + Version: Ubuntu Linux 16.04 64-bit
- Firefox Version: 67.0

**Comment by maxxcrawford** [comment] 2020-01-12 01:01
Duplicate of #402

**Closed by maxxcrawford** 2020-01-12 01:01 UTC
Labels: as-expected
