### ISSUE TITLE
script is causing extension to hang

### ISSUE THREAD

**Issue by a1whte** [mozilla/contain-facebook#450] opened 2019-06-25 12:56 UTC
- Facebook Container Version: 2.0
- Operating System + Version:  Max OS X 10.11.6
- Firefox Version: 67.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status: Font Finder 0.3.3

### Steps to reproduce
1. Got to https://www.theguardian.com/ 
2. Click a live feed page (e.g. politics live)
3.

**Comment by maxxcrawford** [comment] 2019-06-26 16:55
I'm not able to reproduce that – matching your specs (both with and without Font Finder. 

I used the following URL: https://www.theguardian.com/us-news/live/2019/jun/26/donald-trump-fed-chairman-jerome-powell-live-updates-us-election-democratic-debates

How are you interacting with the page? Simply loading it? If possible, please provide additional steps to reproduce.

**Comment by maxxcrawford** [comment] 2019-06-27 21:11
@a1whte Closing for now. Please reopen when you have more steps on how to re-produce!

**Closed by maxxcrawford** 2019-06-27 21:11 UTC
