### ISSUE TITLE
Suggestion: Easy disabling of FB container on a per-website basis

### ISSUE THREAD

**Issue by fortyfive60** [mozilla/contain-facebook#568] opened 2020-01-12 00:46 UTC
I've actually got a couple suggestions...

1. Consider renaming to Social Media Container. I know it's longer but now that it blocks instagram as well, I do think it's nice that it clarifies it a bit. I know I'm less technical than 99% of people on here but also am definitely above average compared to the world in general. I never thought to click on the tiny button on the bottom that reveals that instagram is blocked too. I got confused because I honestly thought it was only facebook. But I wondered for a while (particularly trying to stream stuff) why there were select few sites that just didn't seem to work on FF and was stuck using Chrome (bleh). And that brings me to...  

2. I think there needs to be a simple way of disabling the container functions on a per-website basis easily by clicking a button similar to the way you can easily click on the shield and click the "off" switch on tracking protection. This is helpful when you're viewing a page with a lot of embedded instagram and/or facebook links and you actually _do_ want to see the photos on that website.  

Sorry for wall of text. Let me know if this function is already there and I'm just confused. I would have thought turning off the tracking protections would be enough to disable FB container stuff, but still cant see embeds after refresh.

**Comment by maxxcrawford** [comment] 2020-01-12 01:05
We're considering a settings panel in a future release to include options like allowing Instagram embedded posts

Note that Facebook and Instagram share tracking information with each other so we don't expect to _by default_ not block Instagram. 

We have been discussing internally also updating the add-on description to better highlight that this add-on blocks more than just Facebook, so we appreciate the feedback on that end. 

Marking this as a duplicate of #402 and #370

**Closed by maxxcrawford** 2020-01-12 01:05 UTC
