### ISSUE TITLE
Instagram embedded posts are not showing up

### ISSUE THREAD

**Issue by Franzyd** [mozilla/contain-facebook#520] opened 2019-10-02 15:25 UTC
- Facebook Container Version: 2.0.3
- Operating System + Version: Windows 10 Pro 1903
- Firefox Version: 69.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: Greasemonkey 4.9 (Disabled), Notifier for Gmail™ 0.9.6, Privacy Badger 2019.9.23, Twitch Now 1.1.203

### Actual behavior
Instagram posts embedded on other sites are blank.

### Expected behavior
Instagram posts should at least have a visible, clickable box that opens it in a new container tab.

### Steps to reproduce
Go to a page that has an Instagram post on it.

### Notes
Example on www.knowyourmeme.com :

![Blank spaces](https://i.imgur.com/m0geH6V.png)

**Comment by maxxcrawford** [comment] 2020-01-12 01:01
Duplicate of #402

**Closed by maxxcrawford** 2020-01-12 01:01 UTC
