### ISSUE TITLE
Facebook container modifies the display in certain websites

### ISSUE THREAD

**Issue by viktaur** [mozilla/contain-facebook#861] opened 2022-09-08 12:49 UTC
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Some websites like Wikipedia have a much smaller font-size than it should when the extension is enabled.
![image](https://user-images.githubusercontent.com/30535579/189125969-080a42ef-abc5-4e75-b00c-3aadc2531625.png)

### Expected behavior
The extension should not modify the content display in any way.
![image](https://user-images.githubusercontent.com/30535579/189125842-4e86fb71-f14c-4828-a9fa-af670a0a5aaa.png)

**Comment by fbridault** [comment] 2022-09-08 12:55
I confirm this also happens for me with GitLab and GiHub in dark mode since the last update. The fonts change and some becomes black. I struggled to understand why, but finally I guessed it because I found an extra CSS applied with styles prefixed by `fbc`. Disabling the extension solves the issue.

![image](https://user-images.githubusercontent.com/8638653/189126932-fe05c492-b568-4331-a668-26c076736de7.png)

**Comment by rocramer** [comment] 2022-09-08 12:59
Same problem. This extension is modifying our CSS since today. (https://www.prigge-recht.de)

Among other things, it is overwriting the font-family and size.

**Comment by ansuz** [comment] 2022-09-08 13:01
> I confirm this also happens for me with GitLab and GiHub in dark mode since the last update. The fonts change and some becomes black. I struggled to understand why, but finally I guessed it because I found an extra CSS applied with styles prefixed by fbc. Disabling the extension solves the issue.

Same for me. It seems there's a `color: #15141A;` property being  applied to the `body` in `content_script.css`. Toggling this property off in the inspector fixes it in place for every site where I've observed the behaviour. I've also disabled the extension entirely for now.

**Comment by RVxLab** [comment] 2022-09-08 13:01
> I confirm this also happens for me with GitLab and GiHub in dark mode since the last update. The fonts change and some becomes black. I struggled to understand why, but finally I guessed it because I found an extra CSS applied with styles prefixed by `fbc`. Disabling the extension solves the issue.
> 
> ![image](https://user-images.githubusercontent.com/8638653/189126932-fe05c492-b568-4331-a668-26c076736de7.png)

Looks to be caused by [this line](https://github.com/mozilla/contain-facebook/blob/main/src/content_script.css#L14)

**Comment by mj12albert** [comment] 2022-09-08 13:01
I’m facing a similar issue where it breaks [glances](https://github.com/nicolargo/glances)

In the console I see an error from [here](https://github.com/mozilla/contain-facebook/blob/main/src/content_script.js#L694) – `TypeError: target.querySelectorAll is not a function`

Facebook Container Version: 2.3.3 (`Last Updated 8 September 20221)
Operating System + Version: MacOS 12.5.1
Firefox Version: Firefox 104.0.2 (64-bit)
Other installed Add-ons + Version + Enabled/Disabled-Status: disabled all other addons

**Comment by ansuz** [comment] 2022-09-08 13:02
> > I confirm this also happens for me with GitLab and GiHub in dark mode since the last update. The fonts change and some becomes black. I struggled to understand why, but finally I guessed it because I found an extra CSS applied with styles prefixed by fbc. Disabling the extension solves the issue.
> 
> Same for me. It seems there's a `color: #15141A;` property being applied to the `body` in `content_script.css`. Toggling this property off in the inspector fixes it in place for every site where I've observed the behaviour. I've also disabled the extension entirely for now.

https://github.com/mozilla/contain-facebook/blob/main/src/content_script.css#L14 <- the line in question

**Comment by architchandra** [comment] 2022-09-08 13:14
Happening to me too.

Facebook Container v2.3.3
Firefox v104.0.2
MacOS v12.5.1

**Comment by bakulf** [comment] 2022-09-08 14:05
Version 2.3.3 was buggy and, as a temporary fix, we just released a v2.3.4 as a v2.4.2 repackaged. Please, update the add-on to have a fix for this issue.
All the features introduced by v2.3.3 will be released in v2.3.5 as soon as possible.

**Closed by bakulf** 2022-09-08 14:05 UTC
