### ISSUE TITLE
The Plugin blocks buttons without facebook contact (like Shariff buttons)

### ISSUE THREAD

**Issue by AlbiWe** [mozilla/contain-facebook#441] opened 2019-06-12 05:31 UTC
The detection of Facebook buttons is not yet perfect. For example, the Shariff button is blocked, which is unnecessary. It restricts functionality . 

see https://github.com/heiseonline/shariff

**Comment by maxxcrawford** [comment] 2019-06-14 01:52
This in an ongoing issue currently for non-privacy invading share buttons being badged. 

Marking as a duplicate of #430

**Closed by maxxcrawford** 2019-06-14 01:52 UTC
Labels: duplicate
