### ISSUE TITLE
Dialog is not displayed completely when click the fence icon on a button

### ISSUE THREAD

**Issue by flodolo** [mozilla/contain-facebook#356] opened 2019-05-14 13:50 UTC
Italian build of 1.7.1, title of the dialog is cut off

![Schermata 2019-05-14 alle 15 42 30](https://user-images.githubusercontent.com/3644868/57703251-fa9bdc80-765f-11e9-95b8-f12b55675fda.png)

**Comment by maxxcrawford** [comment] 2019-05-14 15:40
Duplicate of #353

**Closed by maxxcrawford** 2019-05-14 15:40 UTC
Labels: :memo: content script
