### ISSUE TITLE
Messes with tab history

### ISSUE THREAD

**Issue by grzegorz-janoszka** [mozilla/contain-facebook#639] opened 2020-05-12 08:41 UTC
- Facebook Container Version: 2.1.1
- Operating System + Version: Windows 10
- Firefox Version: 76.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: noscript, webex, ubloc origin

### Actual behavior
This addon removes tab history. Going from facebook disabled page to facebook enabled page clears the history.

### Expected behavior
The tab history should be remembered regardless of its facebook status.

### Steps to reproduce
1. Go to 2-3 websites which have facebook disabled.
2. Check history if you have those entries, then go to a facebook enabled page.
3. Tab history is cleared.

### Notes
It is very annoying and removes all the usability of this tab. I cannot press "back" in the browser.

**Comment by maxxcrawford** [comment] 2020-05-13 18:37
Duplicate of #143

**Closed by maxxcrawford** 2020-05-13 18:37 UTC

**Comment by maxxcrawford** [comment] 2020-05-26 15:07
Duplicate of #24
