### ISSUE TITLE
Facebook Container blocks its own website (GitHub.com)

### ISSUE THREAD

**Issue by ryanheise** [mozilla/contain-facebook#576] opened 2020-02-09 12:51 UTC
- Facebook Container Version:2.0.3
- Operating System + Version: Arch Linux 5.4.10-arch1-1 
- Firefox Version: 72.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

Facebook Container pops up on some GitHub issues pages when I try to write an issue comment and doesn't let me click the "Comment" button.

### Expected behavior

Facebook Container and GitHub should not conflict with each other.

### Steps to reproduce
1. Go to https://github.com/roughike/flutter_facebook_login/issues/231
2. Try to write a comment
3. When you either click in the comment box or click on the Comment button, Facebook Container will prevent you with the "Allow Facebook to track you here?" dialog.

If the same doesn't happen to you, it may be a purely random thing, depending on the user and/or geographical location.

### Notes

Probably GitHub is using Facebook tracking on the Comment button of some issues pages, and Facebook Container is just doing its job by preventing me from commenting on GitHub. However, given the mission statement of Facebook Container, to protect you from Facebook tracking, it seems ironic that the project would be hosted on a website that apparently requires you to participate in Facebook tracking if you want it to be functional.

**Comment by maxxcrawford** [comment] 2020-02-12 21:24
When you see a badge on an element, an element on the page matches a pattern in from the [content-script.js](https://github.com/mozilla/contain-facebook/blob/master/src/content_script.js#L45) of the FBC extension. 

In your example, the name of the repo, "flutter_facebook_login" contains **facebook_login** in the string. This trips up some of the patterns, badging elements it shouldn't. 

Specific example, on the star count: 

![image](https://user-images.githubusercontent.com/2692333/74378288-4e805100-4dab-11ea-9535-98b8a5bfa01a.png)

Uses a `form` tag with an action attr  (`<form action="/roughike/flutter_facebook_login/star"...`) that matches [this pattern](https://github.com/mozilla/contain-facebook/blob/master/src/content_script.js#L45): `[action*='facebook_login']`

This is an inherent bug in how the system matches. We're working on a revised pattern library to only run patterns on supported/targeted sites. Marking this as a duplicate under it. 

Duplicate of #544

**Closed by maxxcrawford** 2020-02-12 21:24 UTC
