### ISSUE TITLE
Multiple badges are displayed on the page

### ISSUE THREAD

**Issue by obotisan** [mozilla/contain-facebook#331] opened 2019-05-10 11:38 UTC
**Affected versions:**
- Firefox 66.0.5

**Affected Platforms:**
 - Windows 10 x64
- Ubuntu 18.04 x64
- macOS 10.13

**Prerequisites:**
- Have the [facebook_container-1.7.0](https://github.com/mozilla/contain-facebook/releases/tag/1.7.0) add-on installed.

**Steps to reproduce:**

1. Go to https://www.pinterest.com/.
2. From the left top corner, switch between Log In and Sign Up pop-up.

**Expected result:**
- Only one badge is displayed. 

**Actual result:**
- Multiple badges are displayed. 

**Notes:**
- Please see the attached screen recording with the issue: https://drive.google.com/open?id=1dGxH_MnJfvoLnrebgB6OLjiJ1ocLRKJV

**Comment by maxxcrawford** [comment] 2019-05-10 20:06
Same/Duplicate of #332

**Closed by maxxcrawford** 2019-05-10 20:06 UTC

**Comment by obotisan** [comment] 2019-05-13 12:22
Is this the same issue as #332? Because it seems to me that in the bug #332 both the small badge and the large badge are displayed, yet on the other hand in this one the badge remains displayed even if the page is changed. @maxxcrawford

**Comment by obotisan** [comment] 2019-05-20 12:14
@maxxcrawford, I can still reproduce this issue on pinterest.
