### ISSUE TITLE
Please, (add option to) load FB-provided page elements anonymously

### ISSUE THREAD

**Issue by djasa** [mozilla/contain-facebook#479] opened 2019-07-17 09:01 UTC
- Facebook Container Version: 2.0.1
- Operating System + Version: Fedora 30
- Firefox Version: 68.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Chambers (UK)	1.0	true	chambers-en-GB@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.0.1	true	@contain-facebook
Google	1.0	true	google@search.mozilla.org
Image Forward	2.0.6	true	imageforward@sblask
Strict Pop-up Blocker	0.6	true	jid1-P34HaABBBpOerQ@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### Steps to reproduce
1. View user list in this [Strava flyby](https://labs.strava.com/flyby/viewer/#2464198149)
2.
3.

### Actual behavior
Users who linked their profile to FB to provide their image show some ugly placeholder

### Expected behavior
There is an option to load such resources from FB in anonymous way (with as little information as possible sent to facebook - cookies, screen dimensions, plug-ins list, font-list etc.)

**Comment by maxxcrawford** [comment] 2020-01-08 16:32
Duplicate of #370

**Closed by maxxcrawford** 2020-01-08 16:32 UTC
Labels: enhancement
