### ISSUE TITLE
Facebook container needs a way to put sites into the container, Hootsuite failure

### ISSUE THREAD

**Issue by hfball** [mozilla/contain-facebook#575] opened 2020-02-08 05:25 UTC
I recently started a job that requires me to use Hootsuite to manage Facebook Pages webpages.

Problem is, Hootsuite doesn't work properly with Facebook Container operating, because Hootsuite is outside the container and it has to integrate with Facebook.

I tried installing Firefox Multi-account Containers and then using that add-on's menus to tell Containers to always open "hootsuite.com" in the "Facebook" container, but that didn't work.

I'd still like to have Facebook Container look out for my privacy, while having the ability to white list specific domains to work within the Facebook Container and integrate with Facebook.

Is this something that can be accomplished?

Thanks, 

Russ Hansen

**Comment by maxxcrawford** [comment] 2020-02-12 21:32
@hfball Great news! This feature is already in progress (and should been near completion by the end of this week). Follow along the progress here: #422 

Duplicate of #422

**Closed by maxxcrawford** 2020-02-12 21:32 UTC
