### ISSUE TITLE
Duplicate tabs open when opening link from Facebook to a site that is assigned to a different container

### ISSUE THREAD

**Issue by pdehaan** [mozilla/contain-facebook#63] opened 2018-03-28 17:14 UTC
A bug report from a user via the containers@ mailing list: 

> _"When opening a link from Facebook to a site that is assigned to a different container (in my case youtube), it opens up two tabs of the same link/video. Also, it seems that when using the Facebook container, opening links to other sites (that are switched to no container) do not conform to my settings about opening new tabs in the background, but instead switches to the new tab immediately."_

**Comment by stoically** [comment] 2018-03-28 17:29
The duplicate Tab issue might have the same origin as described in https://github.com/mozilla/contain-facebook/issues/48#issuecomment-376909228 - which can be caused by Facebook Container and Multi-Account Containers (the fix in MAC isn't yet published)

Tabs not opening with correct `active` state is similar to #56 - the call to `tabs.create` needs to get `active` from the tab being removed passed in.

**Comment by Softvision-CristinaBadescu** [comment] 2018-03-29 13:43
I've managed to reproduce the duplicate Tab issue using Facebook Containers (v1.2.5), on Windows 10 x64, using latest Firefox Release 59.0.2 (both official version and unbranded one). However, I could not reproduce it on Mac 10.13.3 or Ubuntu 14.04 x64. As mentioned in the above comment, this might have the same root cause as in #48 and we'll track it there.

The tab opening behavior (similar to #56) is no longer reproducible using Facebook Container (v1.2.5) on latest Firefox Release 59.0.2 (both official version and unbranded one), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.

**Comment by stoically** [comment] 2018-03-29 16:03
Fix for the remaining duplicate Tab Issue is available in #68

**Comment by stoically** [comment] 2018-03-30 05:35
Closing as #68 got merged

**Closed by stoically** 2018-03-30 05:35 UTC
Labels: MAC-compatibility, P3, bug, has PR

**Comment by azazello4** [comment] 2020-01-19 14:58
I still face this issue.
